// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var Demo = require("./Demo.bs.js");
var Demo2 = require("./Demo2.bs.js");

console.log(Demo.SubModuleKo.toString(Demo.SubModuleKo.make(/* Foo */ 0)));

console.log(Demo.SubModuleKo.toString(Demo.SubModuleKo.make(/* Bar */ 1)));

console.log(Demo2.SubModuleOk.toString(Demo2.SubModuleOk.make(/* Rachel */ 0)));

console.log(Demo2.SubModuleOk.toString(Demo2.SubModuleOk.make(/* Ross */ 1)));

/*  Not a pure module */
