// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(person) {
  if (person) {
    return {
            name: "Ross",
            lastname: "Geller"
          };
  } else {
    return {
            name: "Rachel",
            lastname: "Green"
          };
  }
}

function toString(param) {
  return "" + param.name + " " + param.lastname + "";
}

var SubModuleOk = {
  make: make,
  toString: toString
};

exports.SubModuleOk = SubModuleOk;
/* No side effect */
